on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: gradle:8.2.1-jdk17
    steps:
      - run: "gradle publish"
